# comments
name: Maven_Build_Example
env:
  JAVA_VERSION : "17"
  DISTRIBUTION : "zulu"
  BROWSER: "chrome-remote"
  suiteXmlFile: "testSuites/tests.xml"
  LOGIN: "Waters"
  PASSWORD: "User135"
on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Step 1 - Checkout master branchfrom Github
      uses: actions/checkout@v4
    
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.DISTRIBUTION }} 
        java-version: ${{ env.JAVA_VERSION }} 
        
    - name: Step 3 - Build with Maven
      run: |
        mvn clean test -DdriverType="$browser" -DsuiteXmlFile="$suiteXmlFile" -Dlogin="$login" -Dpassword="$password"
        mkdir staging && cp target/*.jar staging

    - name: Step 4 - Persist workflow data as artifacts
      uses: actions/upload-artifact@v4 
      with: 
        name: github-actions-artifact
        path: staging
