name: Maven_Build_Example
environment: test
env:
  JAVA_VERSION : "17"
  DISTRIBUTION : "zulu"
  suiteXmlFile: "testSuites/tests.xml"
  LOGIN: ${{ secrets.LOGIN }}
  PASSWORD: ${{ secrets.PASSWORD }}
  BROWSER: "CHROME-REMOTE"
  URL: "https://www.advantageonlineshopping.com/#/"
on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout master branch from Github
      uses: actions/checkout@v4

    - name: Build and run Docker Compose services
      run:  docker compose -f ./docker-compose.yml up -d

    - name: Step 3 - Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.DISTRIBUTION }} 
        java-version: ${{ env.JAVA_VERSION }}

    - name: Step 3 - Build with Maven
      run: |
        echo "login is ${{ env.LOGIN }}"
        echo "password is ${{ env.PASSWORD }}"
        mvn clean test -DsuiteXmlFile="$suiteXmlFile" -Dbrowser="$BROWSER" -Durl="$URL" -Dlogin="$LOGIN" -Dpassword="$PASSWORD" 

    - name: Tear down Docker Compose services
      run: |
        docker compose down