name: Maven_Build_Example
env:
  JAVA_VERSION : "17"
  DISTRIBUTION : "zulu"
  suiteXmlFile: "testSuites/tests.xml"
  login: ${{secrets.LOGIN}}
  password: ${{secrets.PASSWORD}}
on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout master branch from Github
      uses: actions/checkout@v4

    - name: Build and run Docker Compose services
      run:  docker compose -f ./docker-compose.yml up -d


    - name: Step 3 - Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.DISTRIBUTION }} 
        java-version: ${{ env.JAVA_VERSION }}

    - name: Step 3 - Build with Maven
      run: |
        mvn clean test -DsuiteXmlFile="$suiteXmlFile" -Dbrowser="CHROME-REMOTE" -Dlogin=${{secrets.LOGIN}} -Dpassword=${{secrets.PASSWORD}}
        mkdir staging && cp target/*.jar staging

    - name: Step 4 - Persist workflow data as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-actions-artifact
        path: staging

    - name: Tear down Docker Compose services
      run: |
        docker compose down